version: '3.8'

services:
  #--- Layanan Frontend (Vue.js) ---#
  frontend:
    build:
      context: ./frontend
    container_name: recipe_vue_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: recipe_slim_backend
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/vendor
    # ports:
    #   - "8080:80"